### ISSUE TITLE
shows leda as locked (it's not) in my save

### ISSUE THREAD

**Issue by Owyn** [egavard/vampire-survivors-save-edit#13]
![image](https://user-images.githubusercontent.com/1309656/167917950-afa4783b-9182-4a30-96ca-84c5000c57f9.png)
![image](https://user-images.githubusercontent.com/1309656/167918116-bc349e19-2190-46f5-843c-69e829400f70.png)

also shows all arcanas as locked
[SaveData.zip](https://github.com/egavard/vampire-survivors-save-edit/files/8672417/SaveData.zip)

also, what is "shield" power-up which shows as zero as well? it's not in the game...

**Comment by egavard** [comment]
Hi

I fixed the issue with Leda.

The SHIELD is in the PowerUps data of the game but it's seems to be unused at the moment. It's supposed to stack with Laurel
