### ISSUE TITLE
Editor not matching actual save

### ISSUE THREAD

**Issue by subworx** [egavard/vampire-survivors-save-edit#5]
Hi,
thanks for this nice editor. I wasn't able to figure out the file format myself.

Tried it with my save (`C:\Users\xxx\AppData\Roaming\Vampire_Survivors\saves\SaveData.sav`) and the result is quite wrong unfortunately.
I attached the save for you to verify.

The first nine (basic) weapons show as locked, Runetracer and Fire Wand don't, some evoutions I unlocked also show as locked..
Characters mismatch as well, shows Antonio (the starting character) as locked and not bought, Imelda is not unlocked but bought (and I unlocked and bought her ingame).
PowerUps are all correct :)

Due to this I didn't make any change or try if the output actually works.
[SaveData.zip](https://github.com/egavard/vampire-survivors-save-edit/files/8605841/SaveData.zip)

Best regards

**Comment by egavard** [comment]
Hello

Thank you for trying the tool and giving me such feedback 👍 !
It appears that default unlocked and purchased characters are not in the save. That means Antonio is completely absent, and Pasqualina, Imelda and others who are unlocked by default and purchasable, are absent from unlocked chars.

I'll manage that :) 

I still need to take a look at the weapons globally, I did not take the time to see how it works.

**Comment by egavard** [comment]
The current version should fix everything you mentioned.

Here's the results with your save:

![image](https://user-images.githubusercontent.com/7823622/166541743-73ec151f-e4e1-4d0c-a05f-c0f6e78bd5b2.png)

Coming next: Updating unlocked weapons and manage power ups!
